### ISSUE TITLE
[Feature Request] App translations

### ISSUE THREAD

**Issue by mks-h** [aeri/Nihonoari-App#14]
Add app interface translations, and translation of right answers (to be same lang as interface). I can write you Ukrainian and Russian translations.

**Comment by aeri** [comment]
I think it's a good idea, I've never worked with multi-language applications and that's why I didn't implement it, I left it in English because it's a universal language, but I'd also like it to be adapted to the language of the device. 

It doesn't seem to be very difficult given the state of the app where there is little text, I will try to implement it and I count on your help for Russian and Ukrainian :)

**Comment by mks-h** [comment]
F-Droid uses "[Hosted Weblate](https://hosted.weblate.org/)" website for translations, but i'll be fine with git, afaik where to edit.

**Comment by 90-008** [comment]
I can translate the application to Turkish.

**Comment by aeri** [comment]
I have linked a PR with the support of translation, for now there is only Spanish and English, the translation works through JSON, currently there is little text to translate but it can be of much higher quality with human translation. 

It would be great if @dpadar could translate [this JSON](https://github.com/aeri/Nihonoari-App/blob/wip/i18n/en.json) into Ukrainian and Russian and @yusdacra into Turkish. You could send it to me or do PR.

With regard to the romanization of the kanas, as far as I see in Russian it [is different](https://ru.wikipedia.org/wiki/%D0%A0%D1%83_(%D0%BA%D0%B0%D0%BD%D0%B0)), do you propose to accept the entry in Russian?

**Comment by mks-h** [comment]
Can we also translate `fastlane/metadata/android`?

> romanization of the kanas

There is different ways of cyrillization japanese for cyrillic languages - 6 ways in Ukrainian, and probably few in Russian. So I propose having answers defined for each language, with multiple correct options.

Edit: those 6 differ slightly
![Screenshot_20200921_204014](https://user-images.githubusercontent.com/51861383/93801854-552d4b80-fc4b-11ea-8062-085f07152bef.png)

**Comment by aeri** [comment]
> Can we also translate fastlane/metadata/android?

Sure, that is a great idea, i forgetted the fastlane

For the topic of the cyrillization I have to change the engine of the quiz in order to accept in this way several correct answers, however this will come well also for the future inclusion of Kanjis.

I understand that regardless of the language all those answers are correct, I would only have to change the message at the time of failure, in which you would have to show all the possible solutions. This is an interesting challenge.

**Comment by mks-h** [comment]
Then I'm closing this issue and opening new one for i18n. I think we can go with romanji on any ui language, for now. Will add translation soon, today I hope.

**Comment by aeri** [comment]
Perfect, I have already reviewed the other issue and I will ask you something else when implementing it.
