### ISSUE TITLE
Proposal to change kana table layout

### ISSUE THREAD

**Issue by mks-h** [aeri/Nihonoari-App#25]
Hi! I think current table is kinda missing the point of being a table. I edited screenshot to better illustrate my proposal:
![Nihonoari](https://user-images.githubusercontent.com/51861383/97747873-42811e80-1af5-11eb-8fa8-bcd4bef3799b.png)
Edit is kinda misaligned, but whatever...

**Comment by aeri** [comment]
Thank you for the suggerstion, I chose the table based on other tables of the style, basically what you propose is to replace the first row and first column by the Roman characters.

I don't know what convinces me more, however i think it would be meaningless when the Cyrillic characters are incorporated.

**Comment by mks-h** [comment]
On current layout, katakana and romaji are little bit hard to read. Also, navigating by romaji is more logical, because other way it requires you to know some kana, in order to find forgotten kana.
I think it can be i18n-ed just fine, at least for Cyrillic.

**Comment by aeri** [comment]
Finally I have chosen to include in the frames, the letters in romaji because as you say it makes navigation much easier, however I do not want to get rid of the romaji inside the box because it is useful for kanas that are not represented with the combination of two letters such as shi chi, tsu, etc.

![](https://i.imgur.com/y46zRhL.png)

I have also increased the size of the Katakana to make it easier to read.
