### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [aeri/Nihonoari-App#41]
https://monitor.f-droid.org/builds/log/com.LAPARCELA.nihonoari/10#site-footer 

https://issuetracker.google.com/issues/184872412 This is an issue of AGP 4.1. Updating AGP to 4.2 or above should fix it. Could you please upgrade the AGP? Thanks!

**Comment by aeri** [comment]
I am confused about this, I have had an error when compiling with a clean, isolated installation of Flutter 2.5.3 on GNU/Linux as specified in the [build manifest](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.LAPARCELA.nihonoari.yml).

This failure was due to a problem replacing the applicationName value in the AndroidManifest, now In the commit https://github.com/aeri/Nihonoari-App/commit/448f61cf1f19d715830d9fdddff1dc3cdf7843c4 the problem is fixed, however, the bug reported by the F-Droid build seems to have nothing to do with this,

Apparently it's a problem with AAPT2 but I'm not sure if it's in the code or in the compiling machine, I might as well update the Gradle version.

**Comment by aeri** [comment]
I updated the Gardle build tool version in a new commit (https://github.com/aeri/Nihonoari-App/commit/d98b87efa6ddfe2529756c51ed33701febbcd55c), could this solve the problem? I understand that I will have to delete the current release and re-publish it for F-Droid to pick up the changes.

**Comment by linsui** [comment]
Hopefully this can solve the problem. You don't need to re-tag the release. I'll update the build metadata. Thanks!

**Comment by linsui** [comment]
https://monitor.f-droid.org/builds/log/com.LAPARCELA.nihonoari/10#site-footer It builds. Thanks!

**Comment by aeri** [comment]
Great, thanks for the heads up.
